[package]
name = "nl-utils"
version = "0.1.0"
authors = ["Tabor Kelly <taborkelly@gmail.com>"]

[dependencies]
getopts = "0.2"
log = "0.3.0"
env_logger = "0.3.0"
pcap = "0.3.2"
libc = "0.1.0"
byteorder = "0.3.0"
enum_primitive = "0.1.0"
num = "0.1.0"
