// this is where the NetlinkFamily enum was generated by build.rs
include!(concat!(env!("OUT_DIR"), "/netlink_family.rs"));
// this is where the NlMsgType enum was generated by build.rs
include!(concat!(env!("OUT_DIR"), "/nl_msg_type.rs"));
